language: php

# required for installing PHP extensions
sudo: true

php:
    - 7.2

before_install:
    # Spryker required extensions
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - sudo add-apt-repository ppa:ondrej/php -y # "-y" for skipping "Enter" reuqired message
    - sudo apt-get update
    - sudo apt-get install php-gmp php-bz2

install:
    - composer install

script:
    # spryker
    - bin/run prepare --project spryker
    - bin/run analyze --project spryker
    - bin/run ecs --project spryker
    - bin/run phpstan --project spryker

notifications:
    email: false
